[package]
name = "garden-server"
version = "0.1.0"
authors = ["Eran Cohen <ceranco@gmail.com>"]
edition = "2018"

[dependencies]
garden-rpc = { path = "../garden-rpc" }
tokio = { version = "0.2.22", features = ["macros"] }
tonic = "0.3.1"
chrono = "0.4.15"
