[package]
name = "grpc-worker"
version = "0.1.0"
authors = ["Eran Cohen <ceranco@gmail.com>"]
edition = "2018"

[dependencies]
tonic = "0.3.1"
prost = "0.6.1"
tokio = { version = "0.2.22", features = ["macros"] }

[build-dependencies]
tonic-build = "0.3.1"
